name: Deploy Frontend

on:
  push:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1 拉代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 安装依赖
      - name: Install dependencies
        run: |
          npm install

      # 3 打包
      - name: Build project
        run: |
          npm run docs:build

      # 4 部署到服务器目录
      - name: Deploy to server
        run: |
          echo "开始部署..."

          TARGET_DIR=/var/www/blogs/prod

          # 删除旧文件
          sudo rm -rf $TARGET_DIR/*

          # 复制新文件
          sudo cp -r dist/* $TARGET_DIR/

          echo "部署完成"
